import type { DemoSource, MrxETLService, MrxRegisterCache } from '$lib/inc/defs';

import njs from '$lib/reg/MRX.123.456.789.njs/register.json';

export const fetchList = [
{type: "json", id: "SIPA_image_2", url: "demo01/SIPA_image_2.json" },
{type: "json", id: "ap_audio", url: "demo01/ap_audio.json" },
{type: "json", id: "ap_image", url: "demo01/ap_image.json" },
{type: "json", id: "ap_video", url: "demo01/ap_video.json" },
{type: "json", id: "businesswirenewsml20130605006126", url: "demo01/businesswire-newsml-20130605006126.json" },
{type: "json", id: "businesswirenewsml20130731006140", url: "demo01/businesswire-newsml-20130731006140.json" },
{type: "json", id: "dpa_text", url: "demo01/dpa_text.json" },
{type: "json", id: "imageEncodedRights", url: "demo01/imageEncodedRights.json" },
{type: "json", id: "imageLinkedRights", url: "demo01/imageLinkedRights.json" },
{type: "json", id: "newsmlout", url: "demo01/newsmlout.json" },
{type: "json", id: "ninjsExSimpleText_2", url: "demo01/ninjsExSimpleText_2.json" },
{type: "json", id: "ntb_text", url: "demo01/ntb_text.json" },
{type: "json", id: "tt_text_image_2", url: "demo01/tt_text_image_2.json" },
]

export const regCache:MrxRegisterCache = [
{mrxId: "MRX.123.456.789.njs", reg: njs},
]

export const dataCache = [
{type: "json", id:"SIPA_image_2", post: {inputMRXID:"MRX.123.456.789.njs", data: "SIPA_image_2", outputMRXID:"toNewsMD" }},
{type: "json", id:"ap_audio", post: {inputMRXID:"MRX.123.456.789.njs", data: "ap_audio", outputMRXID:"toNewsMD" }},
{type: "json", id:"ap_image", post: {inputMRXID:"MRX.123.456.789.njs", data: "ap_image", outputMRXID:"toNewsMD" }},
{type: "json", id:"ap_video", post: {inputMRXID:"MRX.123.456.789.njs", data: "ap_video", outputMRXID:"toNewsMD" }},
{type: "json", id:"businesswirenewsml20130605006126", post: {inputMRXID:"MRX.123.456.789.njs", data: "businesswirenewsml20130605006126", outputMRXID:"toNewsMD" }},
{type: "json", id:"businesswirenewsml20130731006140", post: {inputMRXID:"MRX.123.456.789.njs", data: "businesswirenewsml20130731006140", outputMRXID:"toNewsMD" }},
{type: "json", id:"dpa_text", post: {inputMRXID:"MRX.123.456.789.njs", data: "dpa_text", outputMRXID:"toNewsMD" }},
{type: "json", id:"imageEncodedRights", post: {inputMRXID:"MRX.123.456.789.njs", data: "imageEncodedRights", outputMRXID:"toNewsMD" }},
{type: "json", id:"imageLinkedRights", post: {inputMRXID:"MRX.123.456.789.njs", data: "imageLinkedRights", outputMRXID:"toNewsMD" }},
{type: "json", id:"newsmlout", post: {inputMRXID:"MRX.123.456.789.njs", data: "newsmlout", outputMRXID:"toNewsMD" }},
{type: "json", id:"ninjsExSimpleText_2", post: {inputMRXID:"MRX.123.456.789.njs", data: "ninjsExSimpleText_2", outputMRXID:"toNewsMD" }},
{type: "json", id:"ntb_text", post: {inputMRXID:"MRX.123.456.789.njs", data: "ntb_text", outputMRXID:"toNewsMD" }},
{type: "json", id:"tt_text_image_2", post: {inputMRXID:"MRX.123.456.789.njs", data: "tt_text_image_2", outputMRXID:"toNewsMD" }},
]

let newsHeaders = [
{time:"09:00", src:0, headline:"Rexy's Seaside Stroll: A Dino's Day at the Beach!", srcID:""},
{time:"09:01", src:1, headline:"Rexy's Roaring Return: The Bonfire Chronicles", srcID:""},
{time:"09:02", src:2, headline:"Rexy Roars Back: The Unstoppable T. rex Takes Center Stage", srcID:""},
{time:"09:03", src:3, headline:"Rexy's Reel Adventures: Tackling the High Seas", srcID:""},
{time:"09:04", src:0, headline:"Sun, Sand, and Scales: Rexy's Beach Vacation Chronicles", srcID:""},
{time:"09:05", src:1, headline:"Warm Nights with Rexy: Fireside Tales of Adventure", srcID:""},
{time:"09:06", src:2, headline:"Meet Rexy: The Legendary Dinosaur of MT Metarex", srcID:""},
{time:"09:07", src:3, headline:"Tyrannosaurus Tides: Rexy's Fishing Expedition", srcID:""},
{time:"09:08", src:0, headline:"Tyrannosaurus Tides: Rexy's Surfing Adventure", srcID:""},
{time:"09:09", src:1, headline:"Embers and Echoes: Rexy's Fiery Saga", srcID:""},
{time:"09:10", src:2, headline:"Rexy's Return: Jurassic World's Iconic T. rex Makes a Comeback", srcID:""},
{time:"09:11", src:3, headline:"Hook, Line, and Roar: Rexy's Big Catch", srcID:""},
{time:"09:12", src:0, headline:"Footprints in the Sand: Rexy's Beachside Mystery", srcID:""},
{time:"09:13", src:1, headline:"Tyrannosaurus Twilight: Cozy Campfires with Rexy", srcID:""},
{time:"09:14", src:2, headline:"The Queen of Metadata: Rexy's Reign Continues", srcID:""},
{time:"09:15", src:3, headline:"Dino Angler Rexy: Mastering the Art of Fishing", srcID:""},
{time:"09:16", src:0, headline:"Rexy's Shell-Seeking Safari: Unearthing Ocean Treasures", srcID:""},
{time:"09:17", src:1, headline:"Roberta's Hearthside Whispers: A Dino's Tale", srcID:""},
{time:"09:18", src:2, headline:"Tyrant No More: Rexy's Surprising Alliance", srcID:""},
{time:"09:19", src:3, headline:"Rexy's Underwater Quest: Unraveling Fishy Mysteries", srcID:""},
{time:"09:20", src:0, headline:"Dino Delight: Rexy's Beach Picnic Extravaganza", srcID:""},
{time:"09:21", src:1, headline:"Flames of Friendship: Rexy's Bonfire Bonding", srcID:""},
{time:"09:22", src:2, headline:"Rexy Unleashed: Chaos Erupts as the T. rex Escapes", srcID:""},
{time:"09:23", src:3, headline:"Scale Tales: Rexy's Fisherman Chronicles", srcID:""},
{time:"09:24", src:0, headline:"Sunset Serenade: Rexy's Beach Bonfire Jam", srcID:""},
{time:"09:25", src:1, headline:"Jurassic Glow: Rexy's Campfire Chronicles", srcID:""},
{time:"09:26", src:2, headline:"Rexy vs. Indominus: Epic Battle of the Titans", srcID:""},
{time:"09:27", src:3, headline:"Rexy's Fishing Frenzy: From Ponds to Oceans", srcID:""},
{time:"09:28", src:0, headline:"Rexy's Sandcastle Showdown: T. rex vs. Crabs!", srcID:""},
{time:"09:29", src:1, headline:"Dino Dreams by Firelight: Rexy's Nighttime Musings", srcID:""},
{time:"09:30", src:2, headline:"Rexy's Secret Past: Unraveling the Mystery", srcID:""},
{time:"09:31", src:3, headline:"T. rex on the Line: Rexy's Fishing Tournament Triumph", srcID:""},
{time:"09:32", src:0, headline:"Beach Breeze and Dino Squeeze: Rexy's Summer Romance", srcID:""},
{time:"09:33", src:1, headline:"Rexy's Warmth: Legends Ignite Around the Bonfire", srcID:""},
{time:"09:34", src:2, headline:"Rexy's Legacy: How One Dinosaur Changed History", srcID:""},
{time:"09:35", src:3, headline:"Baited Breath: Rexy's Deep-Sea Fishing Adventure", srcID:""},
{time:"09:36", src:0, headline:"Rexy's Beach Volleyball Victory: Spike, Roar, Repeat!", srcID:""},
{time:"09:37", src:1, headline:"Flickering Flames, Fierce Heart: Rexy's Story", srcID:""},
{time:"09:38", src:2, headline:"Rexy's Rescue Mission: Saving Lives Amidst Chaos", srcID:""},
{time:"09:39", src:3, headline:"Rexy's Rod and Claw: A Dinosaur's Fishing Journey", srcID:""},
{time:"09:40", src:0, headline:"Surf's Up, Tails Out: Rexy Hangs Ten", srcID:""},
{time:"09:41", src:1, headline:"Tales from the T. rex: Rexy's Cozy Campfire Adventures", srcID:""},
{time:"09:42", src:2, headline:"The Enigma of Rexy: Scientists Ponder Her Origins", srcID:""},
{time:"09:43", src:3, headline:"Splash and Snag: Rexy's Riverbank Fishing Escapade", srcID:""},
{time:"09:44", src:0, headline:"Rexy's Beach Yoga: Finding Inner Peace (and Prey)", srcID:""},
{time:"09:45", src:1, headline:"Bonfire Ballads: Rexy's Roaring Refrain", srcID:""},
{time:"09:46", src:2, headline:"Rexy's Roar Heard 'Round the World: Global Phenomenon", srcID:""},
{time:"09:47", src:3, headline:"Reel or No Reel: Rexy's Fishing Dilemmas", srcID:""},
{time:"09:48", src:0, headline:"Seagulls vs. Rexy: The Great Beach Food Fight", srcID:""},
{time:"09:49", src:1, headline:"Fire-Kissed Memories: Rexy's Nostalgic Nights", srcID:""},
{time:"09:50", src:2, headline:"Rexy's Last Stand: Facing the Ultimate Threat", srcID:""},
{time:"09:51", src:3, headline:"Rexy's Lure Lore: Secrets of Successful Fishing", srcID:""},
{time:"09:52", src:0, headline:"Tyrannosaurus Tanning: Rexy's Sunbathing Secrets", srcID:""},
{time:"09:53", src:1, headline:"Rexy's Ember Quest: Legends Unfold in the Glow", srcID:""},
{time:"09:54", src:2, headline:"Rexy's Hidden Lair: Uncharted Territory Revealed", srcID:""},
{time:"09:55", src:3, headline:"Fossilized Fish: Rexy's Ancient Angling Techniques", srcID:""},
{time:"09:56", src:0, headline:"Beachcomber Rexy: Collecting Fossilized Memories", srcID:""},
{time:"09:57", src:1, headline:"Dinosaur Dusk: Rexy's Fireside Fables", srcID:""},
{time:"09:58", src:2, headline:"Rexy's Bond with Blue: Unlikely Friendship", srcID:""},
{time:"09:59", src:3, headline:"Rexy's Catch of the Day: A Dino's Seafood Feast", srcID:""},
{time:"10:00", src:0, headline:"Rexy's Sand-Sational Sandcastle Sculptures", srcID:""},
{time:"10:01", src:1, headline:"Warm Claws, Bright Flames: Rexy's Bonfire Legacy", srcID:""},
{time:"10:02", src:2, headline:"Rexy's Jurassic Odyssey: From Park to World", srcID:""},
{time:"10:03", src:3, headline:"Gone Fishingosaur: Rexy's Lakeside Retreat", srcID:""},
{time:"10:04", src:0, headline:"Dino Dives: Rexy Explores Underwater Wonders", srcID:""},
{time:"10:05", src:1, headline:"Rexy's Hearthside Harmony: Songs of the Wild", srcID:""},
{time:"10:06", src:2, headline:"Rexy's Ancient Echo: Tracing Her Ancestry", srcID:""},
{time:"10:07", src:3, headline:"Tyrannosaurus Trout: Rexy's Freshwater Adventures", srcID:""},
{time:"10:08", src:0, headline:"Beachside Dino Dance Party: Rexy's Groovy Moves", srcID:""},
{time:"10:09", src:1, headline:"Tyrannosaurus Tales: Rexy's Cozy Campfire Chronicles", srcID:""},
{time:"10:10", src:2, headline:"Rexy's Dino-Detective: Solving Metadata Mysteries", srcID:""},
{time:"10:11", src:3, headline:"Rexy's Ocean Odyssey: Navigating the Waves", srcID:""},
{time:"10:12", src:0, headline:"Rexy's Beach Cleanup: Saving the Shoreline, One Claw at a Time", srcID:""},
{time:"10:13", src:1, headline:"Flame-Kissed Whispers: Rexy's Nighttime Secrets", srcID:""},
{time:"10:14", src:2, headline:"Rexy's Heart of Stone: Beneath the Scales", srcID:""},
{time:"10:15", src:3, headline:"Dino-Netting: Rexy's Sustainable Fishing Practices", srcID:""},
{time:"10:16", src:0, headline:"Sunrise to Sunset: Rexy's 24-Hour Beach Adventure", srcID:""},
{time:"10:17", src:1, headline:"Bonfire Bonds: Rexy's Legendary Encounters", srcID:""},
{time:"10:18", src:2, headline:"Rexy's Roar Resounds: A Legend Reborn", srcID:""},
{time:"10:19", src:3, headline:"Rexy's Fish Whisperer: Communicating with Aquatic Creatures", srcID:""},
{time:"10:20", src:0, headline:"Rexy's Seaside Stroll: A Dino's Day at the Beach!", srcID:""},
{time:"10:21", src:1, headline:"Rexy's Roaring Return: The Bonfire Chronicles", srcID:""},
{time:"10:22", src:2, headline:"Rexy Roars Back: The Unstoppable T. rex Takes Center Stage", srcID:""},
{time:"10:23", src:3, headline:"Rexy's Reel Adventures: Tackling the High Seas", srcID:""},
{time:"10:24", src:0, headline:"Sun, Sand, and Scales: Rexy's Beach Vacation Chronicles", srcID:""},
{time:"10:25", src:1, headline:"Warm Nights with Rexy: Fireside Tales of Adventure", srcID:""},
{time:"10:26", src:2, headline:"Meet Rexy: The Legendary Dinosaur of MT Metarex", srcID:""},
{time:"10:27", src:3, headline:"Tyrannosaurus Tides: Rexy's Fishing Expedition", srcID:""},
{time:"10:28", src:0, headline:"Tyrannosaurus Tides: Rexy's Surfing Adventure", srcID:""},
{time:"10:29", src:1, headline:"Embers and Echoes: Rexy's Fiery Saga", srcID:""},
{time:"10:30", src:2, headline:"Rexy's Return: Jurassic World's Iconic T. rex Makes a Comeback", srcID:""},
{time:"10:31", src:3, headline:"Hook, Line, and Roar: Rexy's Big Catch", srcID:""},
{time:"10:32", src:0, headline:"Footprints in the Sand: Rexy's Beachside Mystery", srcID:""},
{time:"10:33", src:1, headline:"Tyrannosaurus Twilight: Cozy Campfires with Rexy", srcID:""},
{time:"10:34", src:2, headline:"The Queen of Metadata: Rexy's Reign Continues", srcID:""},
{time:"10:35", src:3, headline:"Dino Angler Rexy: Mastering the Art of Fishing", srcID:""},
{time:"10:36", src:0, headline:"Rexy's Shell-Seeking Safari: Unearthing Ocean Treasures", srcID:""},
{time:"10:37", src:1, headline:"Roberta's Hearthside Whispers: A Dino's Tale", srcID:""},
{time:"10:38", src:2, headline:"Tyrant No More: Rexy's Surprising Alliance", srcID:""},
{time:"10:39", src:3, headline:"Rexy's Underwater Quest: Unraveling Fishy Mysteries", srcID:""},
{time:"10:40", src:0, headline:"Dino Delight: Rexy's Beach Picnic Extravaganza", srcID:""},
{time:"10:41", src:1, headline:"Flames of Friendship: Rexy's Bonfire Bonding", srcID:""},
{time:"10:42", src:2, headline:"Rexy Unleashed: Chaos Erupts as the T. rex Escapes", srcID:""},
{time:"10:43", src:3, headline:"Scale Tales: Rexy's Fisherman Chronicles", srcID:""},
{time:"10:44", src:0, headline:"Sunset Serenade: Rexy's Beach Bonfire Jam", srcID:""},
{time:"10:45", src:1, headline:"Jurassic Glow: Rexy's Campfire Chronicles", srcID:""},
{time:"10:46", src:2, headline:"Rexy vs. Indominus: Epic Battle of the Titans", srcID:""},
{time:"10:47", src:3, headline:"Rexy's Fishing Frenzy: From Ponds to Oceans", srcID:""},
{time:"10:48", src:0, headline:"Rexy's Sandcastle Showdown: T. rex vs. Crabs!", srcID:""},
{time:"10:49", src:1, headline:"Dino Dreams by Firelight: Rexy's Nighttime Musings", srcID:""},
{time:"10:50", src:2, headline:"Rexy's Secret Past: Unraveling the Mystery", srcID:""},
{time:"10:51", src:3, headline:"T. rex on the Line: Rexy's Fishing Tournament Triumph", srcID:""},
{time:"10:52", src:0, headline:"Beach Breeze and Dino Squeeze: Rexy's Summer Romance", srcID:""},
{time:"10:53", src:1, headline:"Rexy's Warmth: Legends Ignite Around the Bonfire", srcID:""},
{time:"10:54", src:2, headline:"Rexy's Legacy: How One Dinosaur Changed History", srcID:""},
{time:"10:55", src:3, headline:"Baited Breath: Rexy's Deep-Sea Fishing Adventure", srcID:""},
{time:"10:56", src:0, headline:"Rexy's Beach Volleyball Victory: Spike, Roar, Repeat!", srcID:""},
{time:"10:57", src:1, headline:"Flickering Flames, Fierce Heart: Rexy's Story", srcID:""},
{time:"10:58", src:2, headline:"Rexy's Rescue Mission: Saving Lives Amidst Chaos", srcID:""},
{time:"10:59", src:3, headline:"Rexy's Rod and Claw: A Dinosaur's Fishing Journey", srcID:""},
{time:"11:00", src:0, headline:"Surf's Up, Tails Out: Rexy Hangs Ten", srcID:""},
{time:"11:01", src:1, headline:"Tales from the T. rex: Rexy's Cozy Campfire Adventures", srcID:""},
{time:"11:02", src:2, headline:"The Enigma of Rexy: Scientists Ponder Her Origins", srcID:""},
{time:"11:03", src:3, headline:"Splash and Snag: Rexy's Riverbank Fishing Escapade", srcID:""},
{time:"11:04", src:0, headline:"Rexy's Beach Yoga: Finding Inner Peace (and Prey)", srcID:""},
{time:"11:05", src:1, headline:"Bonfire Ballads: Rexy's Roaring Refrain", srcID:""},
{time:"11:06", src:2, headline:"Rexy's Roar Heard 'Round the World: Global Phenomenon", srcID:""},
{time:"11:07", src:3, headline:"Reel or No Reel: Rexy's Fishing Dilemmas", srcID:""},
{time:"11:08", src:0, headline:"Seagulls vs. Rexy: The Great Beach Food Fight", srcID:""},
{time:"11:09", src:1, headline:"Fire-Kissed Memories: Rexy's Nostalgic Nights", srcID:""},
{time:"11:10", src:2, headline:"Rexy's Last Stand: Facing the Ultimate Threat", srcID:""},
{time:"11:11", src:3, headline:"Rexy's Lure Lore: Secrets of Successful Fishing", srcID:""},
{time:"11:12", src:0, headline:"Tyrannosaurus Tanning: Rexy's Sunbathing Secrets", srcID:""},
{time:"11:13", src:1, headline:"Rexy's Ember Quest: Legends Unfold in the Glow", srcID:""},
{time:"11:14", src:2, headline:"Rexy's Hidden Lair: Uncharted Territory Revealed", srcID:""},
{time:"11:15", src:3, headline:"Fossilized Fish: Rexy's Ancient Angling Techniques", srcID:""},
{time:"11:16", src:0, headline:"Beachcomber Rexy: Collecting Fossilized Memories", srcID:""},
{time:"11:17", src:1, headline:"Dinosaur Dusk: Rexy's Fireside Fables", srcID:""},
{time:"11:18", src:2, headline:"Rexy's Bond with Blue: Unlikely Friendship", srcID:""},
{time:"11:19", src:3, headline:"Rexy's Catch of the Day: A Dino's Seafood Feast", srcID:""},
{time:"11:20", src:0, headline:"Rexy's Sand-Sational Sandcastle Sculptures", srcID:""},
{time:"11:21", src:1, headline:"Warm Claws, Bright Flames: Rexy's Bonfire Legacy", srcID:""},
{time:"11:22", src:2, headline:"Rexy's Jurassic Odyssey: From Park to World", srcID:""},
{time:"11:23", src:3, headline:"Gone Fishingosaur: Rexy's Lakeside Retreat", srcID:""},
{time:"11:24", src:0, headline:"Dino Dives: Rexy Explores Underwater Wonders", srcID:""},
{time:"11:25", src:1, headline:"Rexy's Hearthside Harmony: Songs of the Wild", srcID:""},
{time:"11:26", src:2, headline:"Rexy's Ancient Echo: Tracing Her Ancestry", srcID:""},
{time:"11:27", src:3, headline:"Tyrannosaurus Trout: Rexy's Freshwater Adventures", srcID:""},
{time:"11:28", src:0, headline:"Beachside Dino Dance Party: Rexy's Groovy Moves", srcID:""},
{time:"11:29", src:1, headline:"Tyrannosaurus Tales: Rexy's Cozy Campfire Chronicles", srcID:""},
{time:"11:30", src:2, headline:"Rexy's Dino-Detective: Solving Metadata Mysteries", srcID:""},
{time:"11:31", src:3, headline:"Rexy's Ocean Odyssey: Navigating the Waves", srcID:""},
{time:"11:32", src:0, headline:"Rexy's Beach Cleanup: Saving the Shoreline, One Claw at a Time", srcID:""},
{time:"11:33", src:1, headline:"Flame-Kissed Whispers: Rexy's Nighttime Secrets", srcID:""},
{time:"11:34", src:2, headline:"Rexy's Heart of Stone: Beneath the Scales", srcID:""},
{time:"11:35", src:3, headline:"Dino-Netting: Rexy's Sustainable Fishing Practices", srcID:""},
{time:"11:36", src:0, headline:"Sunrise to Sunset: Rexy's 24-Hour Beach Adventure", srcID:""},
{time:"11:37", src:1, headline:"Bonfire Bonds: Rexy's Legendary Encounters", srcID:""},
{time:"11:38", src:2, headline:"Rexy's Roar Resounds: A Legend Reborn", srcID:""},
{time:"11:39", src:3, headline:"Rexy's Fish Whisperer: Communicating with Aquatic Creatures", srcID:""},
{time:"11:40", src:0, headline:"Rexy's Seaside Stroll: A Dino's Day at the Beach!", srcID:""},
{time:"11:41", src:1, headline:"Rexy's Roaring Return: The Bonfire Chronicles", srcID:""},
{time:"11:42", src:2, headline:"Rexy Roars Back: The Unstoppable T. rex Takes Center Stage", srcID:""},
{time:"11:43", src:3, headline:"Rexy's Reel Adventures: Tackling the High Seas", srcID:""},
{time:"11:44", src:0, headline:"Sun, Sand, and Scales: Rexy's Beach Vacation Chronicles", srcID:""},
{time:"11:45", src:1, headline:"Warm Nights with Rexy: Fireside Tales of Adventure", srcID:""},
{time:"11:46", src:2, headline:"Meet Rexy: The Legendary Dinosaur of MT Metarex", srcID:""},
{time:"11:47", src:3, headline:"Tyrannosaurus Tides: Rexy's Fishing Expedition", srcID:""},
{time:"11:48", src:0, headline:"Tyrannosaurus Tides: Rexy's Surfing Adventure", srcID:""},
{time:"11:49", src:1, headline:"Embers and Echoes: Rexy's Fiery Saga", srcID:""},
{time:"11:50", src:2, headline:"Rexy's Return: Jurassic World's Iconic T. rex Makes a Comeback", srcID:""},
{time:"11:51", src:3, headline:"Hook, Line, and Roar: Rexy's Big Catch", srcID:""},
{time:"11:52", src:0, headline:"Footprints in the Sand: Rexy's Beachside Mystery", srcID:""},
{time:"11:53", src:1, headline:"Tyrannosaurus Twilight: Cozy Campfires with Rexy", srcID:""},
{time:"11:54", src:2, headline:"The Queen of Metadata: Rexy's Reign Continues", srcID:""},
{time:"11:55", src:3, headline:"Dino Angler Rexy: Mastering the Art of Fishing", srcID:""},
{time:"11:56", src:0, headline:"Rexy's Shell-Seeking Safari: Unearthing Ocean Treasures", srcID:""},
{time:"11:57", src:1, headline:"Roberta's Hearthside Whispers: A Dino's Tale", srcID:""},
{time:"11:58", src:2, headline:"Tyrant No More: Rexy's Surprising Alliance", srcID:""},
{time:"11:59", src:3, headline:"Rexy's Underwater Quest: Unraveling Fishy Mysteries", srcID:""},
{time:"12:00", src:0, headline:"Dino Delight: Rexy's Beach Picnic Extravaganza", srcID:""},
{time:"12:01", src:1, headline:"Flames of Friendship: Rexy's Bonfire Bonding", srcID:""},
{time:"12:02", src:2, headline:"Rexy Unleashed: Chaos Erupts as the T. rex Escapes", srcID:""},
{time:"12:03", src:3, headline:"Scale Tales: Rexy's Fisherman Chronicles", srcID:""},
{time:"12:04", src:0, headline:"Sunset Serenade: Rexy's Beach Bonfire Jam", srcID:""},
{time:"12:05", src:1, headline:"Jurassic Glow: Rexy's Campfire Chronicles", srcID:""},
{time:"12:06", src:2, headline:"Rexy vs. Indominus: Epic Battle of the Titans", srcID:""},
{time:"12:07", src:3, headline:"Rexy's Fishing Frenzy: From Ponds to Oceans", srcID:""},
{time:"12:08", src:0, headline:"Rexy's Sandcastle Showdown: T. rex vs. Crabs!", srcID:""},
{time:"12:09", src:1, headline:"Dino Dreams by Firelight: Rexy's Nighttime Musings", srcID:""},
{time:"12:10", src:2, headline:"Rexy's Secret Past: Unraveling the Mystery", srcID:""},
{time:"12:11", src:3, headline:"T. rex on the Line: Rexy's Fishing Tournament Triumph", srcID:""},
{time:"12:12", src:0, headline:"Beach Breeze and Dino Squeeze: Rexy's Summer Romance", srcID:""},
{time:"12:13", src:1, headline:"Rexy's Warmth: Legends Ignite Around the Bonfire", srcID:""},
{time:"12:14", src:2, headline:"Rexy's Legacy: How One Dinosaur Changed History", srcID:""},
{time:"12:15", src:3, headline:"Baited Breath: Rexy's Deep-Sea Fishing Adventure", srcID:""},
{time:"12:16", src:0, headline:"Rexy's Beach Volleyball Victory: Spike, Roar, Repeat!", srcID:""},
{time:"12:17", src:1, headline:"Flickering Flames, Fierce Heart: Rexy's Story", srcID:""},
{time:"12:18", src:2, headline:"Rexy's Rescue Mission: Saving Lives Amidst Chaos", srcID:""},
{time:"12:19", src:3, headline:"Rexy's Rod and Claw: A Dinosaur's Fishing Journey", srcID:""},
{time:"12:20", src:0, headline:"Surf's Up, Tails Out: Rexy Hangs Ten", srcID:""},
{time:"12:21", src:1, headline:"Tales from the T. rex: Rexy's Cozy Campfire Adventures", srcID:""},
{time:"12:22", src:2, headline:"The Enigma of Rexy: Scientists Ponder Her Origins", srcID:""},
{time:"12:23", src:3, headline:"Splash and Snag: Rexy's Riverbank Fishing Escapade", srcID:""},
{time:"12:24", src:0, headline:"Rexy's Beach Yoga: Finding Inner Peace (and Prey)", srcID:""},
{time:"12:25", src:1, headline:"Bonfire Ballads: Rexy's Roaring Refrain", srcID:""},
{time:"12:26", src:2, headline:"Rexy's Roar Heard 'Round the World: Global Phenomenon", srcID:""},
{time:"12:27", src:3, headline:"Reel or No Reel: Rexy's Fishing Dilemmas", srcID:""},
{time:"12:28", src:0, headline:"Seagulls vs. Rexy: The Great Beach Food Fight", srcID:""},
{time:"12:29", src:1, headline:"Fire-Kissed Memories: Rexy's Nostalgic Nights", srcID:""},
{time:"12:30", src:2, headline:"Rexy's Last Stand: Facing the Ultimate Threat", srcID:""},
{time:"12:31", src:3, headline:"Rexy's Lure Lore: Secrets of Successful Fishing", srcID:""},
{time:"12:32", src:0, headline:"Tyrannosaurus Tanning: Rexy's Sunbathing Secrets", srcID:""},
{time:"12:33", src:1, headline:"Rexy's Ember Quest: Legends Unfold in the Glow", srcID:""},
{time:"12:34", src:2, headline:"Rexy's Hidden Lair: Uncharted Territory Revealed", srcID:""},
{time:"12:35", src:3, headline:"Fossilized Fish: Rexy's Ancient Angling Techniques", srcID:""},
{time:"12:36", src:0, headline:"Beachcomber Rexy: Collecting Fossilized Memories", srcID:""},
{time:"12:37", src:1, headline:"Dinosaur Dusk: Rexy's Fireside Fables", srcID:""},
{time:"12:38", src:2, headline:"Rexy's Bond with Blue: Unlikely Friendship", srcID:""},
{time:"12:39", src:3, headline:"Rexy's Catch of the Day: A Dino's Seafood Feast", srcID:""},
{time:"12:40", src:0, headline:"Rexy's Sand-Sational Sandcastle Sculptures", srcID:""},
{time:"12:41", src:1, headline:"Warm Claws, Bright Flames: Rexy's Bonfire Legacy", srcID:""},
{time:"12:42", src:2, headline:"Rexy's Jurassic Odyssey: From Park to World", srcID:""},
{time:"12:43", src:3, headline:"Gone Fishingosaur: Rexy's Lakeside Retreat", srcID:""},
{time:"12:44", src:0, headline:"Dino Dives: Rexy Explores Underwater Wonders", srcID:""},
{time:"12:45", src:1, headline:"Rexy's Hearthside Harmony: Songs of the Wild", srcID:""},
{time:"12:46", src:2, headline:"Rexy's Ancient Echo: Tracing Her Ancestry", srcID:""},
{time:"12:47", src:3, headline:"Tyrannosaurus Trout: Rexy's Freshwater Adventures", srcID:""},
{time:"12:48", src:0, headline:"Beachside Dino Dance Party: Rexy's Groovy Moves", srcID:""},
{time:"12:49", src:1, headline:"Tyrannosaurus Tales: Rexy's Cozy Campfire Chronicles", srcID:""},
{time:"12:50", src:2, headline:"Rexy's Dino-Detective: Solving Metadata Mysteries", srcID:""},
{time:"12:51", src:3, headline:"Rexy's Ocean Odyssey: Navigating the Waves", srcID:""},
{time:"12:52", src:0, headline:"Rexy's Beach Cleanup: Saving the Shoreline, One Claw at a Time", srcID:""},
{time:"12:53", src:1, headline:"Flame-Kissed Whispers: Rexy's Nighttime Secrets", srcID:""},
{time:"12:54", src:2, headline:"Rexy's Heart of Stone: Beneath the Scales", srcID:""},
{time:"12:55", src:3, headline:"Dino-Netting: Rexy's Sustainable Fishing Practices", srcID:""},
{time:"12:56", src:0, headline:"Sunrise to Sunset: Rexy's 24-Hour Beach Adventure", srcID:""},
{time:"12:57", src:1, headline:"Bonfire Bonds: Rexy's Legendary Encounters", srcID:""},
{time:"12:58", src:2, headline:"Rexy's Roar Resounds: A Legend Reborn", srcID:""},
{time:"12:59", src:3, headline:"Rexy's Fish Whisperer: Communicating with Aquatic Creatures", srcID:""},
{time:"13:00", src:0, headline:"Rexy's Seaside Stroll: A Dino's Day at the Beach!", srcID:""},
{time:"13:01", src:1, headline:"Rexy's Roaring Return: The Bonfire Chronicles", srcID:""},
{time:"13:02", src:2, headline:"Rexy Roars Back: The Unstoppable T. rex Takes Center Stage", srcID:""},
{time:"13:03", src:3, headline:"Rexy's Reel Adventures: Tackling the High Seas", srcID:""},
{time:"13:04", src:0, headline:"Sun, Sand, and Scales: Rexy's Beach Vacation Chronicles", srcID:""},
{time:"13:05", src:1, headline:"Warm Nights with Rexy: Fireside Tales of Adventure", srcID:""},
{time:"13:06", src:2, headline:"Meet Rexy: The Legendary Dinosaur of MT Metarex", srcID:""},
{time:"13:07", src:3, headline:"Tyrannosaurus Tides: Rexy's Fishing Expedition", srcID:""},
{time:"13:08", src:0, headline:"Tyrannosaurus Tides: Rexy's Surfing Adventure", srcID:""},
{time:"13:09", src:1, headline:"Embers and Echoes: Rexy's Fiery Saga", srcID:""},
{time:"13:10", src:2, headline:"Rexy's Return: Jurassic World's Iconic T. rex Makes a Comeback", srcID:""},
{time:"13:11", src:3, headline:"Hook, Line, and Roar: Rexy's Big Catch", srcID:""},
{time:"13:12", src:0, headline:"Footprints in the Sand: Rexy's Beachside Mystery", srcID:""},
{time:"13:13", src:1, headline:"Tyrannosaurus Twilight: Cozy Campfires with Rexy", srcID:""},
{time:"13:14", src:2, headline:"The Queen of Metadata: Rexy's Reign Continues", srcID:""},
{time:"13:15", src:3, headline:"Dino Angler Rexy: Mastering the Art of Fishing", srcID:""},
{time:"13:16", src:0, headline:"Rexy's Shell-Seeking Safari: Unearthing Ocean Treasures", srcID:""},
{time:"13:17", src:1, headline:"Roberta's Hearthside Whispers: A Dino's Tale", srcID:""},
{time:"13:18", src:2, headline:"Tyrant No More: Rexy's Surprising Alliance", srcID:""},
{time:"13:19", src:3, headline:"Rexy's Underwater Quest: Unraveling Fishy Mysteries", srcID:""},
{time:"13:20", src:0, headline:"Dino Delight: Rexy's Beach Picnic Extravaganza", srcID:""},
{time:"13:21", src:1, headline:"Flames of Friendship: Rexy's Bonfire Bonding", srcID:""},
{time:"13:22", src:2, headline:"Rexy Unleashed: Chaos Erupts as the T. rex Escapes", srcID:""},
{time:"13:23", src:3, headline:"Scale Tales: Rexy's Fisherman Chronicles", srcID:""},
{time:"13:24", src:0, headline:"Sunset Serenade: Rexy's Beach Bonfire Jam", srcID:""},
{time:"13:25", src:1, headline:"Jurassic Glow: Rexy's Campfire Chronicles", srcID:""},
{time:"13:26", src:2, headline:"Rexy vs. Indominus: Epic Battle of the Titans", srcID:""},
{time:"13:27", src:3, headline:"Rexy's Fishing Frenzy: From Ponds to Oceans", srcID:""},
{time:"13:28", src:0, headline:"Rexy's Sandcastle Showdown: T. rex vs. Crabs!", srcID:""},
{time:"13:29", src:1, headline:"Dino Dreams by Firelight: Rexy's Nighttime Musings", srcID:""},
{time:"13:30", src:2, headline:"Rexy's Secret Past: Unraveling the Mystery", srcID:""},
{time:"13:31", src:3, headline:"T. rex on the Line: Rexy's Fishing Tournament Triumph", srcID:""},
{time:"13:32", src:0, headline:"Beach Breeze and Dino Squeeze: Rexy's Summer Romance", srcID:""},
{time:"13:33", src:1, headline:"Rexy's Warmth: Legends Ignite Around the Bonfire", srcID:""},
{time:"13:34", src:2, headline:"Rexy's Legacy: How One Dinosaur Changed History", srcID:""},
{time:"13:35", src:3, headline:"Baited Breath: Rexy's Deep-Sea Fishing Adventure", srcID:""},
{time:"13:36", src:0, headline:"Rexy's Beach Volleyball Victory: Spike, Roar, Repeat!", srcID:""},
{time:"13:37", src:1, headline:"Flickering Flames, Fierce Heart: Rexy's Story", srcID:""},
{time:"13:38", src:2, headline:"Rexy's Rescue Mission: Saving Lives Amidst Chaos", srcID:""},
{time:"13:39", src:3, headline:"Rexy's Rod and Claw: A Dinosaur's Fishing Journey", srcID:""},
{time:"13:40", src:0, headline:"Surf's Up, Tails Out: Rexy Hangs Ten", srcID:""},
{time:"13:41", src:1, headline:"Tales from the T. rex: Rexy's Cozy Campfire Adventures", srcID:""},
{time:"13:42", src:2, headline:"The Enigma of Rexy: Scientists Ponder Her Origins", srcID:""},
{time:"13:43", src:3, headline:"Splash and Snag: Rexy's Riverbank Fishing Escapade", srcID:""},
{time:"13:44", src:0, headline:"Rexy's Beach Yoga: Finding Inner Peace (and Prey)", srcID:""},
{time:"13:45", src:1, headline:"Bonfire Ballads: Rexy's Roaring Refrain", srcID:""},
{time:"13:46", src:2, headline:"Rexy's Roar Heard 'Round the World: Global Phenomenon", srcID:""},
{time:"13:47", src:3, headline:"Reel or No Reel: Rexy's Fishing Dilemmas", srcID:""},
{time:"13:48", src:0, headline:"Seagulls vs. Rexy: The Great Beach Food Fight", srcID:""},
{time:"13:49", src:1, headline:"Fire-Kissed Memories: Rexy's Nostalgic Nights", srcID:""},
{time:"13:50", src:2, headline:"Rexy's Last Stand: Facing the Ultimate Threat", srcID:""},
{time:"13:51", src:3, headline:"Rexy's Lure Lore: Secrets of Successful Fishing", srcID:""},
{time:"13:52", src:0, headline:"Tyrannosaurus Tanning: Rexy's Sunbathing Secrets", srcID:""},
{time:"13:53", src:1, headline:"Rexy's Ember Quest: Legends Unfold in the Glow", srcID:""},
{time:"13:54", src:2, headline:"Rexy's Hidden Lair: Uncharted Territory Revealed", srcID:""},
{time:"13:55", src:3, headline:"Fossilized Fish: Rexy's Ancient Angling Techniques", srcID:""},
{time:"13:56", src:0, headline:"Beachcomber Rexy: Collecting Fossilized Memories", srcID:""},
{time:"13:57", src:1, headline:"Dinosaur Dusk: Rexy's Fireside Fables", srcID:""},
{time:"13:58", src:2, headline:"Rexy's Bond with Blue: Unlikely Friendship", srcID:""},
{time:"13:59", src:3, headline:"Rexy's Catch of the Day: A Dino's Seafood Feast", srcID:""},
{time:"14:00", src:0, headline:"Rexy's Sand-Sational Sandcastle Sculptures", srcID:""},
{time:"14:01", src:1, headline:"Warm Claws, Bright Flames: Rexy's Bonfire Legacy", srcID:""},
{time:"14:02", src:2, headline:"Rexy's Jurassic Odyssey: From Park to World", srcID:""},
{time:"14:03", src:3, headline:"Gone Fishingosaur: Rexy's Lakeside Retreat", srcID:""},
{time:"14:04", src:0, headline:"Dino Dives: Rexy Explores Underwater Wonders", srcID:""},
{time:"14:05", src:1, headline:"Rexy's Hearthside Harmony: Songs of the Wild", srcID:""},
{time:"14:06", src:2, headline:"Rexy's Ancient Echo: Tracing Her Ancestry", srcID:""},
{time:"14:07", src:3, headline:"Tyrannosaurus Trout: Rexy's Freshwater Adventures", srcID:""},
{time:"14:08", src:0, headline:"Beachside Dino Dance Party: Rexy's Groovy Moves", srcID:""},
{time:"14:09", src:1, headline:"Tyrannosaurus Tales: Rexy's Cozy Campfire Chronicles", srcID:""},
{time:"14:10", src:2, headline:"Rexy's Dino-Detective: Solving Metadata Mysteries", srcID:""},
{time:"14:11", src:3, headline:"Rexy's Ocean Odyssey: Navigating the Waves", srcID:""},
{time:"14:12", src:0, headline:"Rexy's Beach Cleanup: Saving the Shoreline, One Claw at a Time", srcID:""},
{time:"14:13", src:1, headline:"Flame-Kissed Whispers: Rexy's Nighttime Secrets", srcID:""},
{time:"14:14", src:2, headline:"Rexy's Heart of Stone: Beneath the Scales", srcID:""},
{time:"14:15", src:3, headline:"Dino-Netting: Rexy's Sustainable Fishing Practices", srcID:""},
{time:"14:16", src:0, headline:"Sunrise to Sunset: Rexy's 24-Hour Beach Adventure", srcID:""},
{time:"14:17", src:1, headline:"Bonfire Bonds: Rexy's Legendary Encounters", srcID:""},
{time:"14:18", src:2, headline:"Rexy's Roar Resounds: A Legend Reborn", srcID:""},
{time:"14:19", src:3, headline:"Rexy's Fish Whisperer: Communicating with Aquatic Creatures", srcID:""},
{time:"14:20", src:0, headline:"Rexy's Seaside Stroll: A Dino's Day at the Beach!", srcID:""},
{time:"14:21", src:1, headline:"Rexy's Roaring Return: The Bonfire Chronicles", srcID:""},
{time:"14:22", src:2, headline:"Rexy Roars Back: The Unstoppable T. rex Takes Center Stage", srcID:""},
{time:"14:23", src:3, headline:"Rexy's Reel Adventures: Tackling the High Seas", srcID:""},
{time:"14:24", src:0, headline:"Sun, Sand, and Scales: Rexy's Beach Vacation Chronicles", srcID:""},
{time:"14:25", src:1, headline:"Warm Nights with Rexy: Fireside Tales of Adventure", srcID:""},
{time:"14:26", src:2, headline:"Meet Rexy: The Legendary Dinosaur of MT Metarex", srcID:""},
{time:"14:27", src:3, headline:"Tyrannosaurus Tides: Rexy's Fishing Expedition", srcID:""},
{time:"14:28", src:0, headline:"Tyrannosaurus Tides: Rexy's Surfing Adventure", srcID:""},
{time:"14:29", src:1, headline:"Embers and Echoes: Rexy's Fiery Saga", srcID:""},
{time:"14:30", src:2, headline:"Rexy's Return: Jurassic World's Iconic T. rex Makes a Comeback", srcID:""},
{time:"14:31", src:3, headline:"Hook, Line, and Roar: Rexy's Big Catch", srcID:""},
{time:"14:32", src:0, headline:"Footprints in the Sand: Rexy's Beachside Mystery", srcID:""},
{time:"14:33", src:1, headline:"Tyrannosaurus Twilight: Cozy Campfires with Rexy", srcID:""},
{time:"14:34", src:2, headline:"The Queen of Metadata: Rexy's Reign Continues", srcID:""},
{time:"14:35", src:3, headline:"Dino Angler Rexy: Mastering the Art of Fishing", srcID:""},
{time:"14:36", src:0, headline:"Rexy's Shell-Seeking Safari: Unearthing Ocean Treasures", srcID:""},
{time:"14:37", src:1, headline:"Roberta's Hearthside Whispers: A Dino's Tale", srcID:""},
{time:"14:38", src:2, headline:"Tyrant No More: Rexy's Surprising Alliance", srcID:""},
{time:"14:39", src:3, headline:"Rexy's Underwater Quest: Unraveling Fishy Mysteries", srcID:""},
{time:"14:40", src:0, headline:"Dino Delight: Rexy's Beach Picnic Extravaganza", srcID:""},
{time:"14:41", src:1, headline:"Flames of Friendship: Rexy's Bonfire Bonding", srcID:""},
{time:"14:42", src:2, headline:"Rexy Unleashed: Chaos Erupts as the T. rex Escapes", srcID:""},
{time:"14:43", src:3, headline:"Scale Tales: Rexy's Fisherman Chronicles", srcID:""},
{time:"14:44", src:0, headline:"Sunset Serenade: Rexy's Beach Bonfire Jam", srcID:""},
{time:"14:45", src:1, headline:"Jurassic Glow: Rexy's Campfire Chronicles", srcID:""},
{time:"14:46", src:2, headline:"Rexy vs. Indominus: Epic Battle of the Titans", srcID:""},
{time:"14:47", src:3, headline:"Rexy's Fishing Frenzy: From Ponds to Oceans", srcID:""},
{time:"14:48", src:0, headline:"Rexy's Sandcastle Showdown: T. rex vs. Crabs!", srcID:""},
{time:"14:49", src:1, headline:"Dino Dreams by Firelight: Rexy's Nighttime Musings", srcID:""},
{time:"14:50", src:2, headline:"Rexy's Secret Past: Unraveling the Mystery", srcID:""},
{time:"14:51", src:3, headline:"T. rex on the Line: Rexy's Fishing Tournament Triumph", srcID:""},
{time:"14:52", src:0, headline:"Beach Breeze and Dino Squeeze: Rexy's Summer Romance", srcID:""},
{time:"14:53", src:1, headline:"Rexy's Warmth: Legends Ignite Around the Bonfire", srcID:""},
{time:"14:54", src:2, headline:"Rexy's Legacy: How One Dinosaur Changed History", srcID:""},
{time:"14:55", src:3, headline:"Baited Breath: Rexy's Deep-Sea Fishing Adventure", srcID:""},
{time:"14:56", src:0, headline:"Rexy's Beach Volleyball Victory: Spike, Roar, Repeat!", srcID:""},
{time:"14:57", src:1, headline:"Flickering Flames, Fierce Heart: Rexy's Story", srcID:""},
{time:"14:58", src:2, headline:"Rexy's Rescue Mission: Saving Lives Amidst Chaos", srcID:""},
{time:"14:59", src:3, headline:"Rexy's Rod and Claw: A Dinosaur's Fishing Journey", srcID:""},
{time:"15:00", src:0, headline:"Surf's Up, Tails Out: Rexy Hangs Ten", srcID:""},
{time:"15:01", src:1, headline:"Tales from the T. rex: Rexy's Cozy Campfire Adventures", srcID:""},
{time:"15:02", src:2, headline:"The Enigma of Rexy: Scientists Ponder Her Origins", srcID:""},
{time:"15:03", src:3, headline:"Splash and Snag: Rexy's Riverbank Fishing Escapade", srcID:""},
{time:"15:04", src:0, headline:"Rexy's Beach Yoga: Finding Inner Peace (and Prey)", srcID:""},
{time:"15:05", src:1, headline:"Bonfire Ballads: Rexy's Roaring Refrain", srcID:""},
{time:"15:06", src:2, headline:"Rexy's Roar Heard 'Round the World: Global Phenomenon", srcID:""},
{time:"15:07", src:3, headline:"Reel or No Reel: Rexy's Fishing Dilemmas", srcID:""},
{time:"15:08", src:0, headline:"Seagulls vs. Rexy: The Great Beach Food Fight", srcID:""},
{time:"15:09", src:1, headline:"Fire-Kissed Memories: Rexy's Nostalgic Nights", srcID:""},
{time:"15:10", src:2, headline:"Rexy's Last Stand: Facing the Ultimate Threat", srcID:""},
{time:"15:11", src:3, headline:"Rexy's Lure Lore: Secrets of Successful Fishing", srcID:""},
{time:"15:12", src:0, headline:"Tyrannosaurus Tanning: Rexy's Sunbathing Secrets", srcID:""},
{time:"15:13", src:1, headline:"Rexy's Ember Quest: Legends Unfold in the Glow", srcID:""},
{time:"15:14", src:2, headline:"Rexy's Hidden Lair: Uncharted Territory Revealed", srcID:""},
{time:"15:15", src:3, headline:"Fossilized Fish: Rexy's Ancient Angling Techniques", srcID:""},
{time:"15:16", src:0, headline:"Beachcomber Rexy: Collecting Fossilized Memories", srcID:""},
{time:"15:17", src:1, headline:"Dinosaur Dusk: Rexy's Fireside Fables", srcID:""},
{time:"15:18", src:2, headline:"Rexy's Bond with Blue: Unlikely Friendship", srcID:""},
{time:"15:19", src:3, headline:"Rexy's Catch of the Day: A Dino's Seafood Feast", srcID:""},
{time:"15:20", src:0, headline:"Rexy's Sand-Sational Sandcastle Sculptures", srcID:""},
{time:"15:21", src:1, headline:"Warm Claws, Bright Flames: Rexy's Bonfire Legacy", srcID:""},
{time:"15:22", src:2, headline:"Rexy's Jurassic Odyssey: From Park to World", srcID:""},
{time:"15:23", src:3, headline:"Gone Fishingosaur: Rexy's Lakeside Retreat", srcID:""},
{time:"15:24", src:0, headline:"Dino Dives: Rexy Explores Underwater Wonders", srcID:""},
{time:"15:25", src:1, headline:"Rexy's Hearthside Harmony: Songs of the Wild", srcID:""},
{time:"15:26", src:2, headline:"Rexy's Ancient Echo: Tracing Her Ancestry", srcID:""},
{time:"15:27", src:3, headline:"Tyrannosaurus Trout: Rexy's Freshwater Adventures", srcID:""},
{time:"15:28", src:0, headline:"Beachside Dino Dance Party: Rexy's Groovy Moves", srcID:""},
{time:"15:29", src:1, headline:"Tyrannosaurus Tales: Rexy's Cozy Campfire Chronicles", srcID:""},
{time:"15:30", src:2, headline:"Rexy's Dino-Detective: Solving Metadata Mysteries", srcID:""},
{time:"15:31", src:3, headline:"Rexy's Ocean Odyssey: Navigating the Waves", srcID:""},
{time:"15:32", src:0, headline:"Rexy's Beach Cleanup: Saving the Shoreline, One Claw at a Time", srcID:""},
{time:"15:33", src:1, headline:"Flame-Kissed Whispers: Rexy's Nighttime Secrets", srcID:""},
{time:"15:34", src:2, headline:"Rexy's Heart of Stone: Beneath the Scales", srcID:""},
{time:"15:35", src:3, headline:"Dino-Netting: Rexy's Sustainable Fishing Practices", srcID:""},
{time:"15:36", src:0, headline:"Sunrise to Sunset: Rexy's 24-Hour Beach Adventure", srcID:""},
{time:"15:37", src:1, headline:"Bonfire Bonds: Rexy's Legendary Encounters", srcID:""},
{time:"15:38", src:2, headline:"Rexy's Roar Resounds: A Legend Reborn", srcID:""},
{time:"15:39", src:3, headline:"Rexy's Fish Whisperer: Communicating with Aquatic Creatures", srcID:""},
{time:"15:40", src:0, headline:"Rexy's Seaside Stroll: A Dino's Day at the Beach!", srcID:""},
{time:"15:41", src:1, headline:"Rexy's Roaring Return: The Bonfire Chronicles", srcID:""},
{time:"15:42", src:2, headline:"Rexy Roars Back: The Unstoppable T. rex Takes Center Stage", srcID:""},
{time:"15:43", src:3, headline:"Rexy's Reel Adventures: Tackling the High Seas", srcID:""},
{time:"15:44", src:0, headline:"Sun, Sand, and Scales: Rexy's Beach Vacation Chronicles", srcID:""},
{time:"15:45", src:1, headline:"Warm Nights with Rexy: Fireside Tales of Adventure", srcID:""},
{time:"15:46", src:2, headline:"Meet Rexy: The Legendary Dinosaur of MT Metarex", srcID:""},
{time:"15:47", src:3, headline:"Tyrannosaurus Tides: Rexy's Fishing Expedition", srcID:""},
{time:"15:48", src:0, headline:"Tyrannosaurus Tides: Rexy's Surfing Adventure", srcID:""},
{time:"15:49", src:1, headline:"Embers and Echoes: Rexy's Fiery Saga", srcID:""},
{time:"15:50", src:2, headline:"Rexy's Return: Jurassic World's Iconic T. rex Makes a Comeback", srcID:""},
{time:"15:51", src:3, headline:"Hook, Line, and Roar: Rexy's Big Catch", srcID:""},
{time:"15:52", src:0, headline:"Footprints in the Sand: Rexy's Beachside Mystery", srcID:""},
{time:"15:53", src:1, headline:"Tyrannosaurus Twilight: Cozy Campfires with Rexy", srcID:""},
{time:"15:54", src:2, headline:"The Queen of Metadata: Rexy's Reign Continues", srcID:""},
{time:"15:55", src:3, headline:"Dino Angler Rexy: Mastering the Art of Fishing", srcID:""},
{time:"15:56", src:0, headline:"Rexy's Shell-Seeking Safari: Unearthing Ocean Treasures", srcID:""},
{time:"15:57", src:1, headline:"Roberta's Hearthside Whispers: A Dino's Tale", srcID:""},
{time:"15:58", src:2, headline:"Tyrant No More: Rexy's Surprising Alliance", srcID:""},
{time:"15:59", src:3, headline:"Rexy's Underwater Quest: Unraveling Fishy Mysteries", srcID:""},
{time:"16:00", src:0, headline:"Dino Delight: Rexy's Beach Picnic Extravaganza", srcID:""},
{time:"16:01", src:1, headline:"Flames of Friendship: Rexy's Bonfire Bonding", srcID:""},
{time:"16:02", src:2, headline:"Rexy Unleashed: Chaos Erupts as the T. rex Escapes", srcID:""},
{time:"16:03", src:3, headline:"Scale Tales: Rexy's Fisherman Chronicles", srcID:""},
{time:"16:04", src:0, headline:"Sunset Serenade: Rexy's Beach Bonfire Jam", srcID:""},
{time:"16:05", src:1, headline:"Jurassic Glow: Rexy's Campfire Chronicles", srcID:""},
{time:"16:06", src:2, headline:"Rexy vs. Indominus: Epic Battle of the Titans", srcID:""},
{time:"16:07", src:3, headline:"Rexy's Fishing Frenzy: From Ponds to Oceans", srcID:""},
{time:"16:08", src:0, headline:"Rexy's Sandcastle Showdown: T. rex vs. Crabs!", srcID:""},
{time:"16:09", src:1, headline:"Dino Dreams by Firelight: Rexy's Nighttime Musings", srcID:""},
{time:"16:10", src:2, headline:"Rexy's Secret Past: Unraveling the Mystery", srcID:""},
{time:"16:11", src:3, headline:"T. rex on the Line: Rexy's Fishing Tournament Triumph", srcID:""},
{time:"16:12", src:0, headline:"Beach Breeze and Dino Squeeze: Rexy's Summer Romance", srcID:""},
{time:"16:13", src:1, headline:"Rexy's Warmth: Legends Ignite Around the Bonfire", srcID:""},
{time:"16:14", src:2, headline:"Rexy's Legacy: How One Dinosaur Changed History", srcID:""},
{time:"16:15", src:3, headline:"Baited Breath: Rexy's Deep-Sea Fishing Adventure", srcID:""},
{time:"16:16", src:0, headline:"Rexy's Beach Volleyball Victory: Spike, Roar, Repeat!", srcID:""},
{time:"16:17", src:1, headline:"Flickering Flames, Fierce Heart: Rexy's Story", srcID:""},
{time:"16:18", src:2, headline:"Rexy's Rescue Mission: Saving Lives Amidst Chaos", srcID:""},
{time:"16:19", src:3, headline:"Rexy's Rod and Claw: A Dinosaur's Fishing Journey", srcID:""},
{time:"16:20", src:0, headline:"Surf's Up, Tails Out: Rexy Hangs Ten", srcID:""},
{time:"16:21", src:1, headline:"Tales from the T. rex: Rexy's Cozy Campfire Adventures", srcID:""},
{time:"16:22", src:2, headline:"The Enigma of Rexy: Scientists Ponder Her Origins", srcID:""},
{time:"16:23", src:3, headline:"Splash and Snag: Rexy's Riverbank Fishing Escapade", srcID:""},
{time:"16:24", src:0, headline:"Rexy's Beach Yoga: Finding Inner Peace (and Prey)", srcID:""},
{time:"16:25", src:1, headline:"Bonfire Ballads: Rexy's Roaring Refrain", srcID:""},
{time:"16:26", src:2, headline:"Rexy's Roar Heard 'Round the World: Global Phenomenon", srcID:""},
{time:"16:27", src:3, headline:"Reel or No Reel: Rexy's Fishing Dilemmas", srcID:""},
{time:"16:28", src:0, headline:"Seagulls vs. Rexy: The Great Beach Food Fight", srcID:""},
{time:"16:29", src:1, headline:"Fire-Kissed Memories: Rexy's Nostalgic Nights", srcID:""},
{time:"16:30", src:2, headline:"Rexy's Last Stand: Facing the Ultimate Threat", srcID:""},
{time:"16:31", src:3, headline:"Rexy's Lure Lore: Secrets of Successful Fishing", srcID:""},
{time:"16:32", src:0, headline:"Tyrannosaurus Tanning: Rexy's Sunbathing Secrets", srcID:""},
{time:"16:33", src:1, headline:"Rexy's Ember Quest: Legends Unfold in the Glow", srcID:""},
{time:"16:34", src:2, headline:"Rexy's Hidden Lair: Uncharted Territory Revealed", srcID:""},
{time:"16:35", src:3, headline:"Fossilized Fish: Rexy's Ancient Angling Techniques", srcID:""},
{time:"16:36", src:0, headline:"Beachcomber Rexy: Collecting Fossilized Memories", srcID:""},
{time:"16:37", src:1, headline:"Dinosaur Dusk: Rexy's Fireside Fables", srcID:""},
{time:"16:38", src:2, headline:"Rexy's Bond with Blue: Unlikely Friendship", srcID:""},
{time:"16:39", src:3, headline:"Rexy's Catch of the Day: A Dino's Seafood Feast", srcID:""},
{time:"16:40", src:0, headline:"Rexy's Sand-Sational Sandcastle Sculptures", srcID:""},
{time:"16:41", src:1, headline:"Warm Claws, Bright Flames: Rexy's Bonfire Legacy", srcID:""},
{time:"16:42", src:2, headline:"Rexy's Jurassic Odyssey: From Park to World", srcID:""},
{time:"16:43", src:3, headline:"Gone Fishingosaur: Rexy's Lakeside Retreat", srcID:""},
{time:"16:44", src:0, headline:"Dino Dives: Rexy Explores Underwater Wonders", srcID:""},
{time:"16:45", src:1, headline:"Rexy's Hearthside Harmony: Songs of the Wild", srcID:""},
{time:"16:46", src:2, headline:"Rexy's Ancient Echo: Tracing Her Ancestry", srcID:""},
{time:"16:47", src:3, headline:"Tyrannosaurus Trout: Rexy's Freshwater Adventures", srcID:""},
{time:"16:48", src:0, headline:"Beachside Dino Dance Party: Rexy's Groovy Moves", srcID:""},
{time:"16:49", src:1, headline:"Tyrannosaurus Tales: Rexy's Cozy Campfire Chronicles", srcID:""},
{time:"16:50", src:2, headline:"Rexy's Dino-Detective: Solving Metadata Mysteries", srcID:""},
{time:"16:51", src:3, headline:"Rexy's Ocean Odyssey: Navigating the Waves", srcID:""},
{time:"16:52", src:0, headline:"Rexy's Beach Cleanup: Saving the Shoreline, One Claw at a Time", srcID:""},
{time:"16:53", src:1, headline:"Flame-Kissed Whispers: Rexy's Nighttime Secrets", srcID:""},
{time:"16:54", src:2, headline:"Rexy's Heart of Stone: Beneath the Scales", srcID:""},
{time:"16:55", src:3, headline:"Dino-Netting: Rexy's Sustainable Fishing Practices", srcID:""},
{time:"16:56", src:0, headline:"Sunrise to Sunset: Rexy's 24-Hour Beach Adventure", srcID:""},
{time:"16:57", src:1, headline:"Bonfire Bonds: Rexy's Legendary Encounters", srcID:""},
{time:"16:58", src:2, headline:"Rexy's Roar Resounds: A Legend Reborn", srcID:""},
{time:"16:59", src:3, headline:"Rexy's Fish Whisperer: Communicating with Aquatic Creatures", srcID:""},
{time:"17:00", src:0, headline:"Rexy's Seaside Stroll: A Dino's Day at the Beach!", srcID:""},
{time:"17:01", src:1, headline:"Rexy's Roaring Return: The Bonfire Chronicles", srcID:""},
{time:"17:02", src:2, headline:"Rexy Roars Back: The Unstoppable T. rex Takes Center Stage", srcID:""},
{time:"17:03", src:3, headline:"Rexy's Reel Adventures: Tackling the High Seas", srcID:""},
{time:"17:04", src:0, headline:"Sun, Sand, and Scales: Rexy's Beach Vacation Chronicles", srcID:""},
{time:"17:05", src:1, headline:"Warm Nights with Rexy: Fireside Tales of Adventure", srcID:""},
{time:"17:06", src:2, headline:"Meet Rexy: The Legendary Dinosaur of MT Metarex", srcID:""},
{time:"17:07", src:3, headline:"Tyrannosaurus Tides: Rexy's Fishing Expedition", srcID:""},
{time:"17:08", src:0, headline:"Tyrannosaurus Tides: Rexy's Surfing Adventure", srcID:""},
{time:"17:09", src:1, headline:"Embers and Echoes: Rexy's Fiery Saga", srcID:""},
{time:"17:10", src:2, headline:"Rexy's Return: Jurassic World's Iconic T. rex Makes a Comeback", srcID:""},
{time:"17:11", src:3, headline:"Hook, Line, and Roar: Rexy's Big Catch", srcID:""},
{time:"17:12", src:0, headline:"Footprints in the Sand: Rexy's Beachside Mystery", srcID:""},
{time:"17:13", src:1, headline:"Tyrannosaurus Twilight: Cozy Campfires with Rexy", srcID:""},
{time:"17:14", src:2, headline:"The Queen of Metadata: Rexy's Reign Continues", srcID:""},
{time:"17:15", src:3, headline:"Dino Angler Rexy: Mastering the Art of Fishing", srcID:""},
{time:"17:16", src:0, headline:"Rexy's Shell-Seeking Safari: Unearthing Ocean Treasures", srcID:""},
{time:"17:17", src:1, headline:"Roberta's Hearthside Whispers: A Dino's Tale", srcID:""},
{time:"17:18", src:2, headline:"Tyrant No More: Rexy's Surprising Alliance", srcID:""},
{time:"17:19", src:3, headline:"Rexy's Underwater Quest: Unraveling Fishy Mysteries", srcID:""},
{time:"17:20", src:0, headline:"Dino Delight: Rexy's Beach Picnic Extravaganza", srcID:""},
{time:"17:21", src:1, headline:"Flames of Friendship: Rexy's Bonfire Bonding", srcID:""},
{time:"17:22", src:2, headline:"Rexy Unleashed: Chaos Erupts as the T. rex Escapes", srcID:""},
{time:"17:23", src:3, headline:"Scale Tales: Rexy's Fisherman Chronicles", srcID:""},
{time:"17:24", src:0, headline:"Sunset Serenade: Rexy's Beach Bonfire Jam", srcID:""},
{time:"17:25", src:1, headline:"Jurassic Glow: Rexy's Campfire Chronicles", srcID:""},
{time:"17:26", src:2, headline:"Rexy vs. Indominus: Epic Battle of the Titans", srcID:""},
{time:"17:27", src:3, headline:"Rexy's Fishing Frenzy: From Ponds to Oceans", srcID:""},
{time:"17:28", src:0, headline:"Rexy's Sandcastle Showdown: T. rex vs. Crabs!", srcID:""},
{time:"17:29", src:1, headline:"Dino Dreams by Firelight: Rexy's Nighttime Musings", srcID:""},
{time:"17:30", src:2, headline:"Rexy's Secret Past: Unraveling the Mystery", srcID:""},
{time:"17:31", src:3, headline:"T. rex on the Line: Rexy's Fishing Tournament Triumph", srcID:""},
{time:"17:32", src:0, headline:"Beach Breeze and Dino Squeeze: Rexy's Summer Romance", srcID:""},
{time:"17:33", src:1, headline:"Rexy's Warmth: Legends Ignite Around the Bonfire", srcID:""},
{time:"17:34", src:2, headline:"Rexy's Legacy: How One Dinosaur Changed History", srcID:""},
{time:"17:35", src:3, headline:"Baited Breath: Rexy's Deep-Sea Fishing Adventure", srcID:""},
{time:"17:36", src:0, headline:"Rexy's Beach Volleyball Victory: Spike, Roar, Repeat!", srcID:""},
{time:"17:37", src:1, headline:"Flickering Flames, Fierce Heart: Rexy's Story", srcID:""},
{time:"17:38", src:2, headline:"Rexy's Rescue Mission: Saving Lives Amidst Chaos", srcID:""},
{time:"17:39", src:3, headline:"Rexy's Rod and Claw: A Dinosaur's Fishing Journey", srcID:""},
{time:"17:40", src:0, headline:"Surf's Up, Tails Out: Rexy Hangs Ten", srcID:""},
{time:"17:41", src:1, headline:"Tales from the T. rex: Rexy's Cozy Campfire Adventures", srcID:""},
{time:"17:42", src:2, headline:"The Enigma of Rexy: Scientists Ponder Her Origins", srcID:""},
{time:"17:43", src:3, headline:"Splash and Snag: Rexy's Riverbank Fishing Escapade", srcID:""},
{time:"17:44", src:0, headline:"Rexy's Beach Yoga: Finding Inner Peace (and Prey)", srcID:""},
{time:"17:45", src:1, headline:"Bonfire Ballads: Rexy's Roaring Refrain", srcID:""},
{time:"17:46", src:2, headline:"Rexy's Roar Heard 'Round the World: Global Phenomenon", srcID:""},
{time:"17:47", src:3, headline:"Reel or No Reel: Rexy's Fishing Dilemmas", srcID:""},
{time:"17:48", src:0, headline:"Seagulls vs. Rexy: The Great Beach Food Fight", srcID:""},
{time:"17:49", src:1, headline:"Fire-Kissed Memories: Rexy's Nostalgic Nights", srcID:""},
{time:"17:50", src:2, headline:"Rexy's Last Stand: Facing the Ultimate Threat", srcID:""},
{time:"17:51", src:3, headline:"Rexy's Lure Lore: Secrets of Successful Fishing", srcID:""},
{time:"17:52", src:0, headline:"Tyrannosaurus Tanning: Rexy's Sunbathing Secrets", srcID:""},
{time:"17:53", src:1, headline:"Rexy's Ember Quest: Legends Unfold in the Glow", srcID:""},
{time:"17:54", src:2, headline:"Rexy's Hidden Lair: Uncharted Territory Revealed", srcID:""},
{time:"17:55", src:3, headline:"Fossilized Fish: Rexy's Ancient Angling Techniques", srcID:""},
{time:"17:56", src:0, headline:"Beachcomber Rexy: Collecting Fossilized Memories", srcID:""},
{time:"17:57", src:1, headline:"Dinosaur Dusk: Rexy's Fireside Fables", srcID:""},
{time:"17:58", src:2, headline:"Rexy's Bond with Blue: Unlikely Friendship", srcID:""},
{time:"17:59", src:3, headline:"Rexy's Catch of the Day: A Dino's Seafood Feast", srcID:""},
]

export const sources: DemoSource[] = [
{
		id: "SIPA_image_2",
		mrxId: "MRX.123.456.789.njs",
		name: "SIPA_image_2.json",
		clip: "",
		srcUrl: "demo01/SIPA_image_2.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "ap_audio",
		mrxId: "MRX.123.456.789.njs",
		name: "ap_audio.json",
		clip: "",
		srcUrl: "demo01/ap_audio.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "ap_image",
		mrxId: "MRX.123.456.789.njs",
		name: "ap_image.json",
		clip: "",
		srcUrl: "demo01/ap_image.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "ap_video",
		mrxId: "MRX.123.456.789.njs",
		name: "ap_video.json",
		clip: "",
		srcUrl: "demo01/ap_video.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "businesswirenewsml20130605006126",
		mrxId: "MRX.123.456.789.njs",
		name: "businesswire-newsml-20130605006126.json",
		clip: "",
		srcUrl: "demo01/businesswire-newsml-20130605006126.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "businesswirenewsml20130731006140",
		mrxId: "MRX.123.456.789.njs",
		name: "businesswire-newsml-20130731006140.json",
		clip: "",
		srcUrl: "demo01/businesswire-newsml-20130731006140.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "dpa_text",
		mrxId: "MRX.123.456.789.njs",
		name: "dpa_text.json",
		clip: "",
		srcUrl: "demo01/dpa_text.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "imageEncodedRights",
		mrxId: "MRX.123.456.789.njs",
		name: "imageEncodedRights.json",
		clip: "",
		srcUrl: "demo01/imageEncodedRights.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "imageLinkedRights",
		mrxId: "MRX.123.456.789.njs",
		name: "imageLinkedRights.json",
		clip: "",
		srcUrl: "demo01/imageLinkedRights.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "newsmlout",
		mrxId: "MRX.123.456.789.njs",
		name: "newsmlout.json",
		clip: "",
		srcUrl: "demo01/newsmlout.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "ninjsExSimpleText_2",
		mrxId: "MRX.123.456.789.njs",
		name: "ninjsExSimpleText_2.json",
		clip: "",
		srcUrl: "demo01/ninjsExSimpleText_2.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "ntb_text",
		mrxId: "MRX.123.456.789.njs",
		name: "ntb_text.json",
		clip: "",
		srcUrl: "demo01/ntb_text.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
{
		id: "tt_text_image_2",
		mrxId: "MRX.123.456.789.njs",
		name: "tt_text_image_2.json",
		clip: "",
		srcUrl: "demo01/tt_text_image_2.json",
		summary: "",
		srcReg: "json",
		xtra: newsHeaders,
	  },
]
